project:
  type: website
  output-dir: docs

website:
  title: "Julio Landa" 
  page-footer: 
    center:  "© Julio Landa · {{< year >}}"
  favicon: images/Perfil.jpg
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: cv.qmd
        text: CV
      - href: publicaciones.qmd
        text: Publicaciones
      - href: proyectos.qmd
        text: Proyectos
      - href: contacto.qmd
        text: Contacto

format:
  html:
    theme: flatly
    css: styles.css
    lang: es
    toc: false



